export const Flags = {
  AED: {
    flag: "🇦🇪",
    country: "United Arab Emirates",
    currency: "United Arab Emirates dirham",
    symbol: "Dh",
    default: "No",
  },
  AFN: {
    flag: "🇦🇫",
    country: "Afghanistan",
    currency: "Afghan afghani",
    symbol: "	؋",
    default: "No",
  },
  ALL: {
    flag: "🇦🇱",
    country: "Albania",
    currency: "Albanian Lek",
    symbol: "Lek",
    default: "No",
  },

  AMD: {
    flag: "🇦🇲",
    country: "Armenia",
    currency: "Armenian dram",
    symbol: "	֏",
    default: "No",
  },
  ANG: {
    flag: "🇨🇼",
    country: "Curacao",
    currency: "Netherlands Antillean guilder",
    symbol: "	ƒ",
    default: "No",
  },
  AOA: {
    flag: "🇦🇴",
    country: "Angola",
    currency: "Angolan kwanza",
    symbol: "Kz",
    default: "No",
  },
  ARS: {
    flag: "🇦🇷",
    country: "Argentina",
    currency: "Argentine peso",
    symbol: "$",
    default: "No",
  },
  AUD: {
    flag: "🇦🇺",
    country: "Australia",
    currency: "Australian dollar",
    symbol: "$",
    default: "Yes",
  },
  AWG: {
    flag: "🇦🇼",
    country: "Aruba",
    currency: "Aruban florin",
    symbol: "ƒ",
    default: "No",
  },
  AZN: {
    flag: "🇦🇿",
    country: "Azerbaijan",
    currency: "Azerbaijani manat",
    symbol: "₼",
    default: "No",
  },
  BAM: {
    flag: "🇧🇦",
    country: "Bosnia and Herzegovina",
    currency: "Bosnia and Herzegovina convertible mark",
    symbol: "KM",
    default: "No",
  },
  BBD: {
    flag: "🇧🇧",
    country: "Barbados",
    currency: "Barbadian dollar",
    symbol: "$",
    default: "No",
  },
  BDT: {
    flag: "🇧🇩",
    country: "Bangladesh",
    currency: "Bangladeshi taka",
    symbol: "	৳",
    default: "No",
  },
  BGN: {
    flag: "🇧🇬",
    country: "Bulgaria",
    currency: "Bulgarian lev",
    symbol: "Lev",
    default: "No",
  },
  BHD: {
    flag: "🇧🇭",
    country: "Bahrain",
    currency: "Bahraini dinar",
    symbol: "BD",
    default: "No",
  },
  BIF: {
    flag: "🇧🇮",
    country: "Burundi",
    currency: "Burundian franc",
    symbol: "Fr",
    default: "No",
  },
  BMD: {
    flag: "🇧🇲",
    country: "Bermuda",
    currency: "Bermudian dollar",
    symbol: "$",
    default: "No",
  },
  BND: {
    flag: "🇧🇳",
    country: "Brunei",
    currency: "Brunei dollar",
    symbol: "$",
    default: "No",
  },
  BOB: {
    flag: "🇧🇴",
    country: "Bolivia",
    currency: "Bolivian boliviano",
    symbol: "Bs",
    default: "No",
  },
  BRL: {
    flag: "🇧🇷",
    country: "Brazil",
    currency: "Brazilian real",
    symbol: "R$",
    default: "Yes",
  },
  BSD: {
    flag: "🇧🇸",
    country: "Bahamas",
    currency: "Bahamian dollar",
    symbol: "$",
    default: "No",
  },
  BTN: {
    flag: "🇧🇹",
    country: "Bhutan",
    currency: "Bhutanese ngultrum",
    symbol: "Nu",
    default: "No",
  },
  BWP: {
    flag: "🇧🇼",
    country: "Botswana",
    currency: "Botswana pula",
    symbol: "P",
    default: "No",
  },
  BYN: {
    flag: "🇧🇾",
    country: "Belarus",
    currency: "Belarusian ruble",
    symbol: "Br",
    default: "No",
  },
  BZD: {
    flag: "🇧🇿",
    country: "Belize",
    currency: "Belize dollar",
    symbol: "$",
    default: "No",
  },
  CAD: {
    flag: "🇨🇦",
    country: "Canada",
    currency: "Canadian dollar",
    symbol: "$",
    default: "Yes",
  },
  CDF: {
    flag: "🇨🇩",
    country: "Congo, Democratic Republic of the",
    currency: "Congolese franc",
    symbol: "Fr",
    default: "No",
  },
  CHF: {
    flag: "🇨🇭",
    country: "Switzerland",
    currency: "Swiss franc",
    symbol: "Fr",
    default: "Yes",
  },
  CLP: {
    flag: "🇨🇱",
    country: "Chile",
    currency: "Chilean peso",
    symbol: "$",
    default: "No",
  },
  CNY: {
    flag: "🇨🇳",
    country: "China",
    currency: "Renminbi",
    symbol: "¥",
    default: "Yes",
  },
  COP: {
    flag: "🇨🇴",
    country: "Colombia",
    currency: "Colombian peso",
    symbol: "$",
    default: "No",
  },
  CRC: {
    flag: "🇨🇷",
    country: "Costa Rica",
    currency: "Costa Rican colón",
    symbol: "₡",
    default: "No",
  },
  CUP: {
    flag: "🇨🇺",
    country: "Cuba",
    currency: "Cuban peso",
    symbol: "$",
    default: "No",
  },
  CVE: {
    flag: "🇨🇻",
    country: "Cape Verde",
    currency: "Cape Verdean escudo",
    symbol: "$",
    default: "No",
  },
  CZK: {
    flag: "🇨🇿",
    country: "Czech Republic",
    currency: "Czech koruna",
    symbol: "Kč",
    default: "No",
  },
  DJF: {
    flag: "🇩🇯",
    country: "Djibouti",
    currency: "Djiboutian franc",
    symbol: "Fr",
    default: "No",
  },
  DKK: {
    flag: "🇩🇰",
    country: "Denmark",
    currency: "Danish krone",
    symbol: "kr",
    default: "No",
  },
  DOP: {
    flag: "🇩🇴",
    country: "Dominican Republic",
    currency: "Dominican peso",
    symbol: "Kč",
    default: "No",
  },
  DZD: {
    flag: "🇩🇿",
    country: "Algeria",
    currency: "Algerian dinar",
    symbol: "DA",
    default: "No",
  },
  EGP: {
    flag: "🇪🇬",
    country: "Egypt",
    currency: "Egyptian pound",
    symbol: "LE",
    default: "No",
  },
  ERN: {
    flag: "🇪🇷",
    country: "Eritrea",
    currency: "Eritrean nakfa",
    symbol: "Nkf",
    default: "No",
  },
  ETB: {
    flag: "🇪🇹",
    country: "Ethiopia",
    currency: "Ethiopian birr",
    symbol: "Br",
    default: "No",
  },
  EUR: {
    flag: "🇪🇺",
    country: "European Union",
    currency: "Euro",
    symbol: "€",
    default: "Yes",
  },
  FJD: {
    flag: "🇫🇯",
    country: "Fiji",
    currency: "Fijian dollar",
    symbol: "$",
    default: "No",
  },
  FKP: {
    flag: "🇫🇰",
    country: "Falkland Island",
    currency: "Falkland Islands pound",
    symbol: "£",
    default: "No",
  },
  FOK: {
    flag: "🇫🇴",
    country: "Faroe Islands",
    currency: "Faroese Krona",
    symbol: "FOK",
    default: "No",
  },
  GBP: {
    flag: "🇬🇧",
    country: "United Kingdom",
    currency: "Sterling pound",
    symbol: "£",
    default: "Yes",
  },
  GEL: {
    flag: "🇬🇸",
    country: "Georgia",
    currency: "Georgian lari",
    symbol: "₾",
    default: "No",
  },
  GGP: {
    flag: "🇬🇬",
    country: "Guernsey",
    currency: "Guernsey pound",
    symbol: "£",
    default: "No",
  },
  GHS: {
    flag: "🇬🇭",
    country: "Ghana",
    currency: "Ghanaian cedi",
    symbol: "₵",
    default: "No",
  },
  GIP: {
    flag: "🇬🇮",
    country: "Gibraltar",
    currency: "Gibraltar pound",
    symbol: "£",
    default: "No",
  },
  GMD: {
    flag: "🇬🇲",
    country: "Gambia",
    currency: "Gambian dalasi",
    symbol: "D",
    default: "No",
  },
  GNF: {
    flag: "🇬🇳",
    country: "Guinea",
    currency: "Guinean franc",
    symbol: "Fr",
    default: "No",
  },
  GTQ: {
    flag: "🇬🇹",
    country: "Guatemala",
    currency: "Guatemalan quetzal",
    symbol: "Q",
    default: "No",
  },
  GYD: {
    flag: "🇬🇾",
    country: "Guyana",
    currency: "Guyanese dollar",
    symbol: "$",
    default: "No",
  },
  HKD: {
    flag: "🇭🇰",
    country: "Hong Kong",
    currency: "Hong Kong dollar",
    symbol: "$",
    default: "No",
  },
  HNL: {
    flag: "🇭🇳",
    country: "Honduras",
    currency: "Honduran lempira",
    symbol: "H",
    default: "No",
  },
  HRK: {
    flag: "🇭🇷",
    country: "Croatia",
    currency: "Croatian Kuna",
    symbol: "HRK",
    default: "No",
  },
  HTG: {
    flag: "🇭🇹",
    country: "Haiti",
    currency: "Haitian gourde",
    symbol: "G",
    default: "No",
  },
  HUF: {
    flag: "🇭🇺",
    country: "Hungary",
    currency: "Hungarian forint",
    symbol: "Ft",
    default: "No",
  },
  IDR: {
    flag: "🇮🇩",
    country: "Indonesia",
    currency: "Indonesian rupiah",
    symbol: "Rp",
    default: "No",
  },
  ILS: {
    flag: "🇮🇱",
    country: "Israel",
    currency: "Israeli new shekel",
    symbol: "₪",
    default: "No",
  },
  IMP: {
    flag: "🇮🇲",
    country: "Isle of Man",
    currency: "Man pound",
    symbol: "£",
    default: "No",
  },
  INR: {
    flag: "🇮🇳",
    country: "India",
    currency: "Indian rupee",
    symbol: "₹",
    default: "No",
  },
  IQD: {
    flag: "🇮🇶",
    country: "Iraq",
    currency: "Iraqi dinar",
    symbol: "ID",
    default: "No",
  },
  IRR: {
    flag: "🇮🇷",
    country: "Iran",
    currency: "Iranian rial",
    symbol: "RI",
    default: "No",
  },
  ISK: {
    flag: "🇮🇸",
    country: "Iceland",
    currency: "Icelandic króna",
    symbol: "kr",
    default: "No",
  },
  JEP: {
    flag: "🇯🇪",
    country: "Jersey",
    currency: "Jersey pound",
    symbol: "£",
    default: "No",
  },
  JMD: {
    flag: "🇯🇲",
    country: "Jamaica",
    currency: "Jamaican dollar",
    symbol: "$",
    default: "No",
  },
  JOD: {
    flag: "🇯🇴",
    country: "Jordan",
    currency: "Jordanian dinar",
    symbol: "JD",
    default: "No",
  },
  JPY: {
    flag: "🇯🇵",
    country: "Japan",
    currency: "Japanese yen",
    symbol: "¥",
    default: "Yes",
  },
  KES: {
    flag: "🇰🇪",
    country: "Kenya",
    currency: "Kenyan shilling",
    symbol: "Sh",
    default: "No",
  },
  KGS: {
    flag: "🇰🇬",
    country: "Kyrgyztan",
    currency: "Kyrgyz som",
    symbol: "som",
    default: "No",
  },
  KHR: {
    flag: "🇰🇭",
    country: "Cambodia",
    currency: "Cambodian riel",
    symbol: "៛",
    default: "No",
  },
  KID: {
    flag: "🇰🇮",
    country: "Kiribati",
    currency: "Kiribati dollar.",
    symbol: "$",
    default: "No",
  },
  KMF: {
    flag: "🇰🇲",
    country: "Comoros",
    currency: "Comorian franc",
    symbol: "Fr",
    default: "No",
  },
  KRW: {
    flag: "🇰🇷",
    country: "South Korea",
    currency: "South Korean won",
    symbol: "₩",
    default: "No",
  },
  KWD: {
    flag: "🇰🇼",
    country: "Kuwait",
    currency: "Kuwaiti dinar",
    symbol: "KD",
    default: "No",
  },
  KYD: {
    flag: "🇰🇾",
    country: "Cayman Islands",
    currency: "Cayman Islands dollar",
    symbol: "$",
    default: "No",
  },
  KZT: {
    flag: "🇰🇿",
    country: "Kazakhstan",
    currency: "Kazakhstani tenge",
    symbol: "₸",
    default: "No",
  },
  LAK: {
    flag: "🇱🇦",
    country: "Laos",
    currency: "Lao kip",
    symbol: "₭",
    default: "No",
  },
  LBP: {
    flag: "🇱🇧",
    country: "Lebanon",
    currency: "Lebanese pound",
    symbol: "LL",
    default: "No",
  },
  LKR: {
    flag: "🇱🇰",
    country: "Sri Lanka",
    currency: "Sri Lankan rupee",
    symbol: "Re",
    default: "No",
  },
  LRD: {
    flag: "🇱🇷",
    country: "Liberia",
    currency: "Liberian dollar",
    symbol: "$",
    default: "No",
  },
  LSL: {
    flag: "🇱🇸",
    country: "Lesotho",
    currency: "Lesotho loti",
    symbol: "L",
    default: "No",
  },
  LYD: {
    flag: "🇱🇾",
    country: "Libya",
    currency: "Libyan dinar",
    symbol: "LD",
    default: "No",
  },
  MAD: {
    flag: "🇲🇦",
    country: "Morocco",
    currency: "Moroccan dirham",
    symbol: "DH",
    default: "No",
  },
  MDL: {
    flag: "🇲🇩",
    country: "Moldova",
    currency: "Moldovan leu",
    symbol: "Leu",
    default: "No",
  },
  MGA: {
    flag: "🇲🇬",
    country: "Madagascar",
    currency: "Malagasy ariary",
    symbol: "Ar",
    default: "No",
  },
  MKD: {
    flag: "🇲🇰",
    country: "North Macedonia",
    currency: "Macedonian denar",
    symbol: "DEN",
    default: "No",
  },
  MMK: {
    flag: "🇲🇲",
    country: "Myanmar",
    currency: "Burmese kyat",
    symbol: "K",
    default: "No",
  },
  MNT: {
    flag: "🇲🇳",
    country: "Mongolia",
    currency: "Mongolian tögrögr",
    symbol: "₮",
    default: "No",
  },
  MOP: {
    flag: "🇲🇴",
    country: "Macau",
    currency: "Macanese pataca",
    symbol: "MOP$",
    default: "No",
  },
  MRU: {
    flag: "🇲🇷",
    country: "Mauritania",
    currency: "Mauritanian ouguiya",
    symbol: "UM",
    default: "No",
  },
  MUR: {
    flag: "🇲🇺",
    country: "Mauritius",
    currency: "Mauritian rupee",
    symbol: "Re",
    default: "No",
  },
  MVR: {
    flag: "🇲🇻",
    country: "Maldives",
    currency: "Maldivian rufiyaa",
    symbol: "Rf",
    default: "No",
  },
  MWK: {
    flag: "🇲🇼",
    country: "Malawi",
    currency: "Malawian kwacha",
    symbol: "K",
    default: "No",
  },
  MXN: {
    flag: "🇲🇽",
    country: "Mexico",
    currency: "Mexican peso",
    symbol: "$",
    default: "No",
  },
  MYR: {
    flag: "🇲🇾",
    country: "Malaysia",
    currency: "Malaysian ringgit",
    symbol: "RM",
    default: "No",
  },
  MZN: {
    flag: "🇲🇿",
    country: "Mozambique",
    currency: "Mozambican metical",
    symbol: "Mt",
    default: "No",
  },
  NAD: {
    flag: "🇳🇦",
    country: "Namibia",
    currency: "Namibian dollar",
    symbol: "$",
    default: "No",
  },
  NGN: {
    flag: "🇳🇬",
    country: "Nigeria",
    currency: "Nigerian naira",
    symbol: "₦",
    default: "No",
  },
  NIO: {
    flag: "🇳🇮",
    country: "Nicaragua",
    currency: "Nicaraguan córdoba",
    symbol: "C$",
    default: "No",
  },
  NOK: {
    flag: "🇳🇴",
    country: "Norway",
    currency: "Norwegian krone",
    symbol: "kr",
    default: "No",
  },
  NPR: {
    flag: "🇳🇵",
    country: "Nepal",
    currency: "Nepalese rupee",
    symbol: "Re",
    default: "No",
  },
  NZD: {
    flag: "🇳🇿",
    country: "New Zealand",
    currency: "New Zealand dollar",
    symbol: "$",
    default: "No",
  },
  OMR: {
    flag: "🇴🇲",
    country: "Oman",
    currency: "Omani rial",
    symbol: "RO",
    default: "No",
  },
  PAB: {
    flag: "🇵🇦",
    country: "Panama",
    currency: "Panamanian balboa",
    symbol: "B/",
    default: "No",
  },
  PEN: {
    flag: "🇵🇪",
    country: "Peru",
    currency: "Peruvian sol",
    symbol: "S/",
    default: "No",
  },
  PGK: {
    flag: "🇵🇬",
    country: "Papua New Guinea",
    currency: "Papua New Guinean kina",
    symbol: "K",
    default: "No",
  },
  PHP: {
    flag: "🇵🇭",
    country: "Philippines",
    currency: "Philippine peso",
    symbol: "₱",
    default: "No",
  },
  PKR: {
    flag: "🇵🇰",
    country: "Pakistan",
    currency: "Pakistani rupee",
    symbol: "Re",
    default: "No",
  },
  PLN: {
    flag: "🇵🇱",
    country: "Poland",
    currency: "Polish Zloty",
    symbol: "zł",
    default: "Yes",
  },
  PYG: {
    flag: "🇵🇾",
    country: "Paraguay",
    currency: "Paraguayan guaraní",
    symbol: "₲",
    default: "No",
  },
  QAR: {
    flag: "🇶🇦",
    country: "Qatar",
    currency: "Qatari riyal",
    symbol: "QR",
    default: "No",
  },
  RON: {
    flag: "🇷🇴",
    country: "Romania",
    currency: "Romanian leu",
    symbol: "Leu",
    default: "No",
  },
  RSD: {
    flag: "🇷🇸",
    country: "Serbia",
    currency: "Serbian dinar",
    symbol: "DIN",
    default: "No",
  },
  RUB: {
    flag: "🇷🇺",
    country: "Russia",
    currency: "Russian ruble",
    symbol: "₽",
    default: "No",
  },
  RWF: {
    flag: "🇷🇼",
    country: "Rwanda",
    currency: "Rwandan franc",
    symbol: "Fr",
    default: "No",
  },
  SAR: {
    flag: "🇸🇦",
    country: "Saudia Arabia",
    currency: "Saudi riyal",
    symbol: "RI",
    default: "No",
  },
  SBD: {
    flag: "🇸🇧",
    country: "Solomon Islands",
    currency: "Solomon Islands dollar",
    symbol: "$",
    default: "No",
  },
  SCR: {
    flag: "🇸🇨",
    country: "Seychelles",
    currency: "Seychellois rupee",
    symbol: "Re",
    default: "No",
  },
  SDG: {
    flag: "🇸🇩",
    country: "Sudan",
    currency: "Sudanese pound",
    symbol: "LS",
    default: "No",
  },
  SEK: {
    flag: "🇸🇪",
    country: "Sweden",
    currency: "Swedish krona",
    symbol: "kr",
    default: "No",
  },
  SGD: {
    flag: "🇸🇬",
    country: "Singapore",
    currency: "Singapore dollar",
    symbol: "$",
    default: "No",
  },
  SHP: {
    flag: "🇸🇭",
    country: "Saint Helena",
    currency: "Saint Helena pound",
    symbol: "£",
    default: "No",
  },
  SLE: {
    flag: "🇸🇱",
    country: "Sierra Leonean",
    currency: "Sierra Leonean leone",
    symbol: "Le",
    default: "No",
  },

  SOS: {
    flag: "🇸🇴",
    country: "Somalia",
    currency: "	Somali shilling",
    symbol: "Sh",
    default: "No",
  },
  SRD: {
    flag: "🇸🇷",
    country: "Suriname",
    currency: "Surinamese dollar",
    symbol: "$",
    default: "No",
  },
  SSP: {
    flag: "🇸🇸",
    country: "South Sudan",
    currency: "South Sudanese pound",
    symbol: "LS",
    default: "No",
  },

  SYP: {
    flag: "🇸🇾",
    country: "Syria",
    currency: "Syrian pound",
    symbol: "LS",
    default: "No",
  },
  SZL: {
    flag: "🇸🇿",
    country: "Eswatini",
    currency: "Swazi lilangeni",
    symbol: "L",
    default: "No",
  },
  THB: {
    flag: "🇹🇭",
    country: "Thailand",
    currency: "Thai baht",
    symbol: "฿",
    default: "No",
  },
  TJS: {
    flag: "🇹🇯",
    country: "Tajikistan",
    currency: "Tajikistani somoni",
    symbol: "SM",
    default: "No",
  },
  TMT: {
    flag: "🇹🇲",
    country: "Turkmenistan",
    currency: "Turkmenistani manat",
    symbol: "m",
    default: "No",
  },
  TND: {
    flag: "🇹🇳",
    country: "Tunisia",
    currency: "Tunisian dinar",
    symbol: "DT",
    default: "No",
  },
  TOP: {
    flag: "🇹🇴",
    country: "Tonga",
    currency: "Tongan paʻanga",
    symbol: "T$",
    default: "No",
  },
  TRY: {
    flag: "🇹🇷",
    country: "Turkey",
    currency: "Turkish lira",
    symbol: "₺",
    default: "No",
  },
  TTD: {
    flag: "🇹🇹",
    country: "Trinidad and Tobago",
    currency: "Trinidad and Tobago dollar",
    symbol: "$",
    default: "No",
  },
  TVD: {
    flag: "🇹🇻",
    country: "Tuvalu",
    currency: "Tuvaluan dollar",
    symbol: "$",
    default: "No",
  },
  TWD: {
    flag: "🇹🇼",
    country: "Taiwan",
    currency: "New Taiwan dollar",
    symbol: "$",
    default: "No",
  },
  TZS: {
    flag: "🇹🇿",
    country: "Tanzania",
    currency: "Tanzanian shillingi",
    symbol: "Sh",
    default: "No",
  },
  UAH: {
    flag: "🇺🇦",
    country: "Ukraine",
    currency: "Ukrainian hryvnia",
    symbol: "₴",
    default: "No",
  },
  UGX: {
    flag: "🇺🇬",
    country: "Uganda",
    currency: "Ugandan shilling",
    symbol: "Sh",
    default: "No",
  },
  USD: {
    flag: "🇺🇸",
    country: "United States of America",
    currency: "United States dollar",
    symbol: "$",
    default: "Yes",
  },
  UYU: {
    flag: "🇺🇾",
    country: "Uruguay",
    currency: "Uruguayan peso",
    symbol: "$",
    default: "No",
  },
  UZS: {
    flag: "🇺🇿",
    country: "Uzbekistan",
    currency: "Uzbekistani sum",
    symbol: "soum",
    default: "No",
  },
  VES: {
    flag: "🇻🇪",
    country: "Venezuela",
    currency: "Venezuelan sovereign bolívar",
    symbol: "Bs.S",
    default: "No",
  },
  VND: {
    flag: "🇻🇳",
    country: "Vietnam",
    currency: "Vietnamese đồng",
    symbol: "₫",
    default: "No",
  },
  VUV: {
    flag: "🇻🇺",
    country: "Vanuatu",
    currency: "Vanuatu vatu",
    symbol: "VT",
    default: "No",
  },
  WST: {
    flag: "🇼🇸",
    country: "Samoa",
    currency: "Samoan tālā",
    symbol: "$",
    default: "No",
  },
  XAF: {
    flag: "🇨🇫",
    country: "Central African Republic",
    currency: "Central African CFA franc",
    symbol: "Fr",
    default: "No",
  },
  XCD: {
    flag: "🇩🇲",
    country: "Dominica",
    currency: "Eastern Caribbean dollar",
    symbol: "$",
    default: "No",
  },
  XOF: {
    flag: "🇸🇳",
    country: "Senegal",
    currency: "West African CFA franc",
    symbol: "Fr",
    default: "No",
  },
  XPF: {
    flag: "🇳🇨",
    country: "New Caledonia",
    currency: "CFP franc",
    symbol: "₣",
    default: "No",
  },
  YER: {
    flag: "🇾🇪",
    country: "Yemen",
    currency: "Yemeni rial",
    symbol: "RI",
    default: "No",
  },
  ZAR: {
    flag: "🇿🇦",
    country: "South Africa",
    currency: "South African rand",
    symbol: "R",
    default: "No",
  },
  ZMW: {
    flag: "🇿🇲",
    country: "Zambia",
    currency: "Zambian kwacha",
    symbol: "K",
    default: "No",
  },
  ZWL: {
    flag: "🇿🇼",
    country: "Zimbabwe",
    currency: "Zimbabwean Dollar",
    symbol: "$",
    default: "No",
  },
};
